name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r dbf_exe_project/requirements.txt
          pip install pyinstaller

      - name: Build EXE
        working-directory: dbf_exe_project
        run: |
          pyinstaller -F -n PROCONSI-Tanques app.py ^
            --add-data "templates;templates" ^
            --add-data "static;static"

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: PROCONSI-Tanques_EXE
          path: dbf_exe_project/dist/PROCONSI-Tanques.exe
