name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    # Para los "run:" usa cmd y trabaja dentro de la carpeta del proyecto
    defaults:
      run:
        shell: cmd
        working-directory: dbf_exe_project

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show project files (debug)
        run: |
          echo ==== contenido de dbf_exe_project ====
          dir
          echo ==== fin contenido ====

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --clean --name app --onefile ^
            --add-data "templates;templates" ^
            --add-data "static;static" ^
            app.py

      - name: List dist (debug)
        run: |
          echo ==== contenido de dist ====
          dir dist
          echo ==== fin contenido ====

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-exe
          # OJO: rutas relativas a la RAÍZ del repo
          path: |
            dbf_exe_project\dist\app.exe
            dbf_exe_project\dist\app\app.exe
          if-no-files-found: error
