name: Build Windows EXE
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dbf_exe_project/requirements.txt
          pip install pyinstaller
      - name: Build EXE with PyInstaller
        shell: pwsh
        run: py -m PyInstaller -F -n PROCONSI-Tanques dbf_exe_project/app.py --add-data "dbf_exe_project/templates;templates" --add-data "dbf_exe_project/static;static"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PROCONSI-Tanques-EXE
          path: dist/PROCONSI-Tanques.exe
