name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dbf_exe_project/requirements.txt
          python -m pip install pyinstaller

      - name: Ensure static and templates exist
        shell: pwsh
        run: |
          if (-Not (Test-Path "dbf_exe_project\static")) { New-Item -ItemType Directory -Path "dbf_exe_project\static" | Out-Null }
          if (-Not (Test-Path "dbf_exe_project\templates")) { New-Item -ItemType Directory -Path "dbf_exe_project\templates" | Out-Null }

      - name: Build EXE (PyInstaller)
        working-directory: dbf_exe_project
        shell: pwsh
        run: python -m PyInstaller -F -n "PROCONSI-Tanques" app.py --add-data "templates;templates" --add-data "static;static"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PROCONSI-Tanques-exe
          path: dbf_exe_project/dist/*
