name: Build Windows EXE
on: { workflow_dispatch: {} }
jobs:
  build:
    runs-on: windows-latest
    env: { proyecto_dir: dbf_exe_project }
    steps:
      - uses: actions/checkout@v4
      - name: Debug estructura
        run: |
          echo Raiz del repo:
          dir /b
          echo ----
          echo Contenido de %proyecto_dir%:
          dir %proyecto_dir% /b
        shell: cmd
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Instalar dependencias
        run: |
          cd %proyecto_dir%
          py -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        shell: cmd
      - name: Compilar EXE (incluye templates/static)
        run: |
          cd %proyecto_dir%
          pyinstaller -F -n PROCONSI-Tanques app.py ^
            --add-data "templates;templates" ^
            --add-data "static;static"
        shell: cmd
      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: PROCONSI-Tanques_EXE
          path: dbf_exe_project\dist\PROCONSI-Tanques.exe

