name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dbf_exe_project/requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        working-directory: dbf_exe_project
        run: |
          pyinstaller app.py `
            --name "PROCONSI-Tanques" `
            --onefile `
            --console `
            --add-data "templates;templates" `
            --add-data "static;static"

      - name: Debug run of the EXE (log output only)
        working-directory: dbf_exe_project/dist
        run: |
          .\PROCONSI-Tanques.exe || echo "EXE run failed"

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: proconsi-tanques-exe
          path: dbf_exe_project/dist/PROCONSI-Tanques.exe
          if-no-files-found: error
