name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          cd dbf_exe_project
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: |
          cd dbf_exe_project
          pyinstaller --noconfirm --onefile ^
            --name PROCONSI-Tanques ^
            --add-data "templates;templates" ^
            --add-data "static;static" ^
            app.py
          dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PROCONSI-Tanques
          path: dbf_exe_project/dist/PROCONSI-Tanques.exe
