name: Build Windows EXE
on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: dbf_exe_project
    steps:
      - uses: actions/checkout@v4
      - name: Show project files (debug)
        run: dir
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --clean --name app --onefile ^
            --add-data "templates;templates" ^
            --add-data "static;static" ^
            app.py
      - name: List dist (debug)
        run: dir dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-exe
          path: |
            dbf_exe_project\distpp.exe
            dbf_exe_project\distpppp.exe
          if-no-files-found: error
