name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      proyecto_dir: dbf_exe_project
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show tree
        run: |
          echo %CD%
          dir /b
          echo ----
          dir %proyecto_dir% /b
        shell: cmd
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          cd %proyecto_dir%
          py -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        shell: cmd
      - name: Build EXE
        run: |
          cd %proyecto_dir%
          pyinstaller -F -n PROCONSI-Tanques app.py ^
            --add-data "templates;templates" ^
            --add-data "static;static"
        shell: cmd
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PROCONSI-Tanques_EXE
          path: dbf_exe_project\dist\PROCONSI-Tanques.exe
